### PR TITLE
README Italian translation

### PR DESCRIPTION
**Pull request by rogierz**
### Description

This contribution adds the Italian translation of README.

### Pull request checklist

- [ ] Changes added to [data.csv](https://github.com/SkalskiP/courses/blob/master/automation/data.csv). Read contribution [guidelines](https://github.com/SkalskiP/courses/blob/master/CONTRIBUTING.md) to learn more.
- [ ] Changes added to [README.md](https://github.com/SkalskiP/courses/blob/master/automation/data.csv) Read contribution [guidelines](https://github.com/SkalskiP/courses/blob/master/CONTRIBUTING.md) to learn more.
- [x] Pull request description added

### CODE REVIEW

**Comment by SkalskiP** [comment]
Hi @rogierz! Thanks a lot, my 🇮🇹 friend! I left a few comments. Could you help me with that before we merge?

**Comment by rogierz** [comment]
Hi @SkalskiP, I would be glad to help, where can I find the comments you wrote?

**Review by SkalskiP — CHANGES_REQUESTED** [review]

**Comment by rogierz** [comment]
@SkalskiP now everything should be ok, I hope it can be merged :)

**Comment by SkalskiP** [comment]
Looks good merged!

**Pull request merged**
