### PR TITLE
Added courses from W&B on LLM's

### PR DESCRIPTION
**Pull request by sagar118**
Weights & Bias have recently introduced two new courses on LLMs.

Building LLM-Powered Apps
Training and Fine-tuning Large Language Models (LLMs)

### CODE REVIEW

**Comment by SkalskiP** [comment]
Looks like this course is not out yet: https://www.wandb.courses/courses/training-fine-tuning-LLMs ?

**Comment by SkalskiP** [comment]
Seems like it is the same story for: https://www.wandb.courses/courses/building-llm-powered-apps

**Comment by sagar118** [comment]
Thank you for bringing this to my attention. I apologize for any confusion. On Twitter they announced the courses and I was able to enroll for the same. Hence, I might have missed that.

**Comment by sagar118** [comment]
Should I close this PR?

**Comment by SkalskiP** [comment]
Noooo let’s keep the PR open. And when W&B release the tutorials I’m super happy to take a look 👀

**Comment by sagar118** [comment]
Thank you to keep the PR open and look forward to your feedback when the tutorials are released.

**Comment by SkalskiP** [comment]
W&B is in no hurry to publish these resources...

**Comment by sagar118** [comment]
Yeah, seems that way! What do you propose we do with this PR?

**Comment by SkalskiP** [comment]
Sorry @sagar118 🙏🏻 But I think we will close it for now. There is a lot of movement on this repo right now. And I need to clean as many of those hanging PRs as possible. But feel free to reopen it when W&B finally releases it. We will test it and possibly add it if it is good. I'm actually super excited about those courses.

**Comment by sagar118** [comment]
No problem @SkalskiP ✌🏻I completely understand your decision to close the pull request at this time. I appreciate the offer to reopen the pull request once W&B is released.

**Comment by SkalskiP** [comment]
I hope we will see this PR once again soon!

**Pull request closed without merging**
